### ISSUE TITLE
Can't predict images from a CSV file on Kaggle

### ISSUE THREAD

**Issue by EdVieira** [uber/ludwig#229]
I'm tring to train a model and predict some data for an image classification problem on Kaggle, although I have read-only access I used those 'skip_save' parameters to disable file creation:

obs: train_file is a string
```
train_stats = ludwig_model.train(data_csv=train_file,
                                skip_save_model=True,
                                skip_save_progress=True,
                                skip_save_log=True,
                                skip_save_processed_input=True,
                                logging_level=0)
```

I've tried using pandas DataFrame for training and predicting using the data_df instead of data_csv as parameter, but it raised a similar error, until I prepare a custom dataset for properly refer to the image file path on the CSV column (still not working the df option), then it was able to be trained, but... Now it can't predict from the submission file, because "'DataFrame' object has no attribute 'csv'" that is caused when running the line:

obs: test_file is a string
```
predictions = ludwig_model.test(data_csv=test_file,
                                   #data_df=test_df,
                                   return_type='dict',
                                  logging_level=0)
```

It raised:

```
DEBUG:root:Preprocessing 57458 datapoints
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-5893f61b9736> in <module>()
      2                                    #data_df=test_df,
      3                                    return_type='dict',
----> 4                                   logging_level=0)

/opt/conda/lib/python3.6/site-packages/ludwig/api.py in test(self, data_df, data_csv, data_dict, return_type, batch_size, gpus, gpu_fraction, logging_level)
    989             gpu_fraction=gpu_fraction,
    990             only_predictions=False,
--> 991             logging_level=logging_level,
    992         )
    993 

/opt/conda/lib/python3.6/site-packages/ludwig/api.py in _predict(self, data_df, data_csv, data_dict, return_type, batch_size, gpus, gpu_fraction, only_predictions, logging_level)
    772             features_to_load,
    773             self.train_set_metadata,
--> 774             self.model_definition['preprocessing']
    775         )
    776         replace_text_feature_level(self.model_definition, [preprocessed_data])

/opt/conda/lib/python3.6/site-packages/ludwig/data/preprocessing.py in build_data(dataset_df, features, train_set_metadata, global_preprocessing_parameters)
    163             data,
    164             train_set_metadata,
--> 165             preprocessing_parameters
    166         )
    167     return data

/opt/conda/lib/python3.6/site-packages/ludwig/features/image_feature.py in add_feature_data(feature, dataset_df, data, metadata, preprocessing_parameters)
     55             preprocessing_parameters
     56     ):
---> 57         csv_path = os.path.dirname(os.path.abspath(dataset_df.csv))
     58         an_image = imread(
     59             os.path.join(csv_path, dataset_df[feature['name']][0])

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   4374             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   4375                 return self[name]
-> 4376             return object.__getattribute__(self, name)
   4377 
   4378     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'csv'
```

Here is the link to the kernel:
https://www.kaggle.com/edhenrivi/testing-for-image-classification

**Comment by w4nderlust** [comment]
Thanks @EdVieira  , this is likely aalready addressed by this PR: https://github.com/uber/ludwig/pull/219
Can you please try to use it and tell us if it solves the problem for you?

**Comment by EdVieira** [comment]
After reading it I did some changes, but the same error is now raised on the method train_online instead of predict.
I changed the model_definition to:
```
model_definition = {
    "input_features": [{
            "name": "id",
            "type": "image",
            "encoder": "stacked_cnn"
        }
    ], 
    "output_features": [{
            "name": "label", 
            "type": "binary"
        }
     ],
    "training": {
        "epochs": 10,
        "dropout": 0.4,
        'bucketin_field':None
    },
    'data_hdf5_fp':'',
    'vocab_size':200
}
ludwig_model = LudwigModel(model_definition,
                           logging_level=0)
```

For initialize it with:
```
ludwig_model.initialize_model(
    train_set_metadata={
        "id": {
            "height": 96,
            "in_memory": True,
            "num_channels": 3,
            "width": 96
        },
        "label": {
            "preprocessing": {
                "fill_value": 0,
                "missing_value_strategy": "fill_with_const"
            }
        }
  },
  #train_set_metadata_json='metadata_js',
  gpus=None,
  gpu_fraction=1,
  random_seed=42,
  logging_level=0,
  debug=True
)
```

Then call train_online:
```
train_stats = ludwig_model.train_online(data_df=train_df,
                                #skip_save_model=True,
                                #skip_save_progress=True,
                                #skip_save_log=True,
                                #skip_save_processed_input=True,
                                logging_level=0)
```

Got the same error, but now on training:
```
DEBUG:root:Preprocessing 220025 datapoints
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-be087c09f800> in <module>()
      5                                 #skip_save_log=True,
      6                                 #skip_save_processed_input=True,
----> 7                                 logging_level=0)

/opt/conda/lib/python3.6/site-packages/ludwig/api.py in train_online(self, data_df, data_csv, data_dict, batch_size, learning_rate, regularization_lambda, dropout_rate, bucketing_field, gpus, gpu_fraction, logging_level)
    720             features_to_load,
    721             self.train_set_metadata,
--> 722             self.model_definition['preprocessing']
    723         )
    724         replace_text_feature_level(self.model_definition, [preprocessed_data])

/opt/conda/lib/python3.6/site-packages/ludwig/data/preprocessing.py in build_data(dataset_df, features, train_set_metadata, global_preprocessing_parameters)
    163             data,
    164             train_set_metadata,
--> 165             preprocessing_parameters
    166         )
    167     return data

/opt/conda/lib/python3.6/site-packages/ludwig/features/image_feature.py in add_feature_data(feature, dataset_df, data, metadata, preprocessing_parameters)
     55             preprocessing_parameters
     56     ):
---> 57         csv_path = os.path.dirname(os.path.abspath(dataset_df.csv))
     58         an_image = imread(
     59             os.path.join(csv_path, dataset_df[feature['name']][0])

/opt/conda/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   4374             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   4375                 return self[name]
-> 4376             return object.__getattribute__(self, name)
   4377 
   4378     def __setattr__(self, name, value):

AttributeError: 'DataFrame' object has no attribute 'csv'
```

**Comment by EdVieira** [comment]
Now `train_df` or `train_csv` raises the same

**Comment by ydudin3** [comment]
@EdVieira did you reinstall ludwig after you switched to this branch? 
(pip uninstall ludwig && pip install ludwig)

**Comment by w4nderlust** [comment]
We merged the PR in master, can you please confirm that using it (pull and reinstall with setup.py please) the issue is solved?

**Comment by George3d6** [comment]
I'm getting the same issue: (`AttributeError: 'DataFrame' object has no attribute 'csv'`) when trying to train an image model using a dataframe (`data_ft`).

Pulling the latest master and reinstalling via `python3 setup.py install` did not fix the issue.

**Comment by w4nderlust** [comment]
@George3d6  please provide a fully reproducible example (yaml, csv, data or a python script using the api)

**Comment by w4nderlust** [comment]
Closing due to inactivity, but this issue has already been solved on master since a while.
