### ISSUE TITLE
Ludwig predicts different value on jupyter notebook kernel restart

### ISSUE THREAD

**Issue by Chee-Foong** [uber/ludwig#421]
**Describe the bug**
Running on Jupyter Notebook.  Ludwig model predicts a different target label each time I restart the kernel even though there is no change to input data, model definition or trained model.  Using fixed default random seed.

** My Code **
````
model = LudwigModel.load('../model/api_experiment_ludwig_3/model')
testdata = pd.read_csv('../data/doc-class-test.csv')

predictions = model.predict(testdata)
model.close()

predictions.to_csv('../output/doc-class-predict.csv', index=False)
````
** My Model Definition **

```
input_features:
    -
        name: person
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: money
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: organisation
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: text
        type: text
        level: word
        encoder: parallel_cnn
    -
        name: w_acceptance
        type: numerical
    -
        name: w_offer
        type: numerical
    -
        name: w_letter
        type: numerical
    -
        name: w_congratulations
        type: numerical
    -
        name: w_invoice
        type: numerical
    -
        name: w_statement
        type: numerical
    -
        name: w_account
        type: numerical
    -
        name: w_total
        type: numerical
    -
        name: w_amount
        type: numerical
    -
        name: w_payable
        type: numerical
    -
        name: n_17
        type: numerical
    -
        name: n_18
        type: numerical
    -
        name: n_19
        type: numerical


output_features:
    -
        name: doctype
        type: category

training:
        epochs: 100  # Default - 100
        batch_size: 128 # Default - 128

```
 
**Expected behavior**
I am expecting a prediction result to be the same given in the inputs and models are the same.

**Environment (please complete the following information):**
 - OS: Ubuntu 16
- Python 3.5.2
- Ludwig 0.1.2

**Additional context**
Let me know if my understanding of Ludwig is not correct.

**Comment by w4nderlust** [comment]
Let me look into it.

**Comment by w4nderlust** [comment]
I looked into it. Created a synthetic dataset, trained a model and tested by loading the model in another notebook, which I run several times and the results where all the same. So I'm closing this issue also due to inactivity.
If you are still experiencing the issue, please make a reproducible example. I'm attaching my example so that you can eventually use it as a reference.

[issue_421_test.zip](https://github.com/uber/ludwig/files/3419294/issue_421_test.zip)

**Comment by Chee-Foong** [comment]
Hi, Thank you for looking into this.  Sorry for the late reply.  Using your dataset, I replicated the problem in the python notebook.  The steps to reproduce the issue in the notebook - issue_421_train.ipynb.  

After a model is trained, when I restart the kernel, using the same test data, I am getting different predictions.  Not all the time.  You may have to repeat the predictions a few times.

[issue_421_test.zip](https://github.com/uber/ludwig/files/3426226/issue_421_test.zip)

**Comment by w4nderlust** [comment]
I tested this again, using the `issue_421_train.ipynb` from your zip. I restarted the kernel and obtained prediction 10 times and all of the times the predictions were the same.
Now, because this issue has be open for a while, I can't be sure if there was a problem and it has just been solved in the meantime or if there was no problem to begin with and the different predictions were an artifact of something weird in your setup, but anyway, if possible, please test it again using the latest version of ludwig from master `pip uninstall ludwig & pip install git+http://github.comuber/ludwig.git` an confrim if it is solved for you or if you still have problems.

**Comment by Chee-Foong** [comment]
Thank you for looking into this.  I will do as per your suggestion.  Do you prefer to close this issue and that I raise new one if I still encounter similar problems?

**Comment by w4nderlust** [comment]
I'll keep this open. Please test it out and in case the problem is solved I'll close. Also, I suggest creating a fresh new virtualenv when installing from master, just to be sure all dependencies are fine.

**Comment by w4nderlust** [comment]
@Chee-Foong any update on this? Did you try it out?

**Comment by edgetrader** [comment]
Hi, Sorry for the late reply.  I finally found time to test this.  I ran the updated notebook a couple of times with the latest ludwig==0.2.2.4.  See attached zip file.  Prediction results are consistent.  

I am using a new dataset too: [http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/reuters-allcats-6.zip]

I believe you can close this issue.  Thanks for your patience!

[issue_421_test_updated.zip](https://github.com/uber/ludwig/files/4428953/issue_421_test_updated.zip)

**Comment by Chee-Foong** [comment]
Hi, Sorry for the late reply.

I finally found time to test this. I ran the updated notebook a couple of times with the latest ludwig==0.2.2.4. See attached zip file. Prediction results are consistent.

I am using a new dataset too: [Reuters Dataset](http://boston.lti.cs.cmu.edu/classes/95-865-K/HW/HW2/reuters-allcats-6.zip)

I believe you can close this issue. Thanks for your patience!

[issue_421_test_updated.zip](https://github.com/uber/ludwig/files/4429020/issue_421_test_updated.zip)

**Comment by w4nderlust** [comment]
@Chee-Foong thank you so much for confirming it!
